# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 768)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(1024, 768))
        Form.setMaximumSize(QtCore.QSize(1024, 768))
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 991, 641))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab_3)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 10, 951, 400))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 0, 2, 1, 1)
        self.addUserButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.addUserButton.setObjectName("addUserButton")
        self.gridLayout_2.addWidget(self.addUserButton, 2, 1, 1, 1)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.lineEdit_2_1 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_2_1.setObjectName("lineEdit_2_1")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2_1)
        self.gridLayout_2.addLayout(self.formLayout_5, 1, 2, 1, 1)
        self.checkBookButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.checkBookButton.setObjectName("checkBookButton")
        self.gridLayout_2.addWidget(self.checkBookButton, 2, 2, 1, 1)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_1_1 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_1_1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_1_1.setMaxLength(11)
        self.lineEdit_1_1.setPlaceholderText("PESEL")
        self.lineEdit_1_1.setObjectName("lineEdit_1_1")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_1_1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lineEdit_1_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_1_2.setMaxLength(50)
        self.lineEdit_1_2.setPlaceholderText("Imię")
        self.lineEdit_1_2.setObjectName("lineEdit_1_2")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_1_2)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.lineEdit_1_3 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_1_3.setMaxLength(50)
        self.lineEdit_1_3.setPlaceholderText("np. Kowalski")
        self.lineEdit_1_3.setObjectName("lineEdit_1_3")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_1_3)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.lineEdit_1_4 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_1_4.setInputMethodHints(QtCore.Qt.ImhDate)
        self.lineEdit_1_4.setText("")
        self.lineEdit_1_4.setMaxLength(10)
        self.lineEdit_1_4.setPlaceholderText("1900-01-01")
        self.lineEdit_1_4.setObjectName("lineEdit_1_4")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_1_4)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.lineEdit_1_5 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_1_5.setMaxLength(50)
        self.lineEdit_1_5.setPlaceholderText("np. Poznań")
        self.lineEdit_1_5.setObjectName("lineEdit_1_5")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_1_5)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.lineEdit_1_6 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_1_6.setMaxLength(50)
        self.lineEdit_1_6.setPlaceholderText("np. poznański")
        self.lineEdit_1_6.setObjectName("lineEdit_1_6")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_1_6)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.lineEdit_1_7 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_1_7.setMaxLength(50)
        self.lineEdit_1_7.setPlaceholderText("np. Wielkopolska")
        self.lineEdit_1_7.setObjectName("lineEdit_1_7")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_1_7)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.lineEdit_1_8 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_1_8.setText("")
        self.lineEdit_1_8.setPlaceholderText("np. 42")
        self.lineEdit_1_8.setObjectName("lineEdit_1_8")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEdit_1_8)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.lineEdit_1_9 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_1_9.setPlaceholderText("np. Słoneczna")
        self.lineEdit_1_9.setObjectName("lineEdit_1_9")
        self.formLayout_3.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEdit_1_9)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_17.setObjectName("label_17")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.lineEdit_1_10 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_1_10.setMaxLength(6)
        self.lineEdit_1_10.setPlaceholderText("np. 60-680")
        self.lineEdit_1_10.setObjectName("lineEdit_1_10")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lineEdit_1_10)
        self.gridLayout_2.addLayout(self.formLayout_3, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 0, 0, 1, 1)
        self.borrowButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.borrowButton.setObjectName("borrowButton")
        self.gridLayout_2.addWidget(self.borrowButton, 2, 0, 1, 1)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_0_1 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_0_1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_0_1.setMaxLength(11)
        self.lineEdit_0_1.setPlaceholderText("PESEL")
        self.lineEdit_0_1.setClearButtonEnabled(True)
        self.lineEdit_0_1.setObjectName("lineEdit_0_1")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_0_1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox.setMaximum(1000000)
        self.spinBox.setObjectName("spinBox")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox)
        self.spinBox_2 = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.spinBox_2.setMaximum(120)
        self.spinBox_2.setProperty("value", 14)
        self.spinBox_2.setObjectName("spinBox_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBox_2)
        self.gridLayout_2.addLayout(self.formLayout_2, 1, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableView = QtWidgets.QTableView(self.tab)
        self.tableView.setEnabled(True)
        self.tableView.setGeometry(QtCore.QRect(10, 70, 951, 521))
        self.tableView.setObjectName("tableView")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(10, 0, 231, 26))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 951, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchButton = QtWidgets.QPushButton(self.tab)
        self.searchButton.setGeometry(QtCore.QRect(710, 0, 251, 32))
        self.searchButton.setObjectName("searchButton")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.layoutWidget = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget.setGeometry(QtCore.QRect(590, 50, 351, 72))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.deleteButton = QtWidgets.QPushButton(self.layoutWidget)
        self.deleteButton.setObjectName("deleteButton")
        self.verticalLayout.addWidget(self.deleteButton)
        self.addButton = QtWidgets.QPushButton(self.layoutWidget)
        self.addButton.setObjectName("addButton")
        self.verticalLayout.addWidget(self.addButton)
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 43, 26))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_2.setGeometry(QtCore.QRect(70, 10, 331, 26))
        self.comboBox_2.setObjectName("comboBox_2")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(19, 50, 550, 461))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Biblioteka"))
        self.label_19.setText(_translate("Form", "Sprawdź egzemplarz"))
        self.addUserButton.setText(_translate("Form", "Zatwierdź"))
        self.label_18.setText(_translate("Form", "Id egzemplarza*"))
        self.checkBookButton.setText(_translate("Form", "Sprawdź"))
        self.label_6.setText(_translate("Form", "Pesel*"))
        self.label_7.setText(_translate("Form", "Imię*"))
        self.label_8.setText(_translate("Form", "Nazwisko*"))
        self.label_9.setText(_translate("Form", "Data urodzenia*"))
        self.label_10.setText(_translate("Form", "Miasto*"))
        self.label_11.setText(_translate("Form", "Powiat*"))
        self.label_14.setText(_translate("Form", "Województwo*"))
        self.label_15.setText(_translate("Form", "Numer lokalu*"))
        self.label_16.setText(_translate("Form", "Ulica*"))
        self.label_17.setText(_translate("Form", "Kod pocztowy*"))
        self.label_12.setText(_translate("Form", "Nowe wypożyczenie"))
        self.borrowButton.setText(_translate("Form", "Wypożycz"))
        self.label_3.setText(_translate("Form", "Pesel*"))
        self.lineEdit_0_1.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">PESEL </span>- 11 znaków</p></body></html>"))
        self.label_4.setText(_translate("Form", "Id egzemplarza*"))
        self.label_5.setText(_translate("Form", "Dni na oddanie*"))
        self.label_13.setText(_translate("Form", "Nowy użytkownik"))
        self.label.setText(_translate("Form", "* - pole obowiązkowe względem kolumny"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Operacje podstawowe"))
        self.searchButton.setText(_translate("Form", "Wyszukaj wg wzorca"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Wyświetlanie"))
        self.deleteButton.setText(_translate("Form", "Usuń"))
        self.addButton.setText(_translate("Form", "Dodaj"))
        self.label_2.setText(_translate("Form", "Tabela:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Modyfikacja"))

